//! MCP server exposing Kanboard helper tools to ACP agents.
//!
//! The server is launched as a stdio subprocess by the ACP session and uses
//! environment variables to locate Kanboard, the configured boards, and the
//! agent's confined working directory.

use std::{env, path::PathBuf};

use rmcp::{
    ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{ServerCapabilities, ServerInfo},
    tool, tool_handler, tool_router,
};
use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::{Value, json};
use tokio::fs;

use crate::{
    AppError,
    config::BoardConfig,
    kanboard::{KanboardApi, KanboardClient, column_lookup, value_id},
};

/// Result type used by MCP tool implementations.
type AppResult<T> = std::result::Result<T, AppError>;

/// Instructions attached to the MCP server metadata.
const TOOL_INSTRUCTIONS: &str = "Kanboard task tools. Use these tools for task files, task comments, subtasks, and moving cards between configured board columns.";

/// RMCP server exposing Kanboard task tools.
#[derive(Debug, Clone)]
pub struct KanboardMcpServer {
    /// Tool router generated by RMCP macros.
    #[allow(dead_code)]
    tool_router: ToolRouter<Self>,
}

impl KanboardMcpServer {
    /// Build a server with all Kanboard tools registered.
    pub fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }
}

impl Default for KanboardMcpServer {
    /// Build the default Kanboard MCP server.
    fn default() -> Self {
        Self::new()
    }
}

/// Parameters for listing task attachments.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct ListAttachments {
    /// Kanboard task id whose files should be listed.
    task_id: i64,
}

/// Parameters for downloading an attachment.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct GetAttachment {
    /// Kanboard file id to download.
    file_id: i64,
    /// Agent-local output path where bytes should be written.
    output_path: String,
}

/// Parameters for deleting an attachment.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct DeleteAttachment {
    /// Kanboard file id to delete.
    file_id: i64,
}

/// Parameters for uploading a file as a task attachment.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct UploadAttachment {
    /// Kanboard project id containing the task.
    project_id: i64,
    /// Kanboard task id that should receive the file.
    task_id: i64,
    /// Agent-local source path to upload.
    path: String,
    /// Optional filename to store in Kanboard.
    filename: Option<String>,
}

/// Parameters for creating a task comment.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct AddComment {
    /// Kanboard task id to comment on.
    task_id: i64,
    /// Markdown comment body.
    comment: String,
}

/// Parameters for creating a subtask.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct AddSubtask {
    /// Parent Kanboard task id.
    task_id: i64,
    /// Subtask title.
    title: String,
    /// Optional Kanboard username to assign.
    assignee: Option<String>,
}

/// Parameters for moving a card to a configured logical column.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct MoveColumn {
    /// Kanboard project id containing the task.
    project_id: i64,
    /// Kanboard task id to move.
    task_id: i64,
    /// Logical target column: `todo`, `working`, `blocked`, or `done`.
    column: String,
    /// Optional swimlane id used when the task payload lacks one.
    swimlane_id: Option<i64>,
}

#[tool_router]
impl KanboardMcpServer {
    /// List files attached to a Kanboard task.
    #[tool(description = "List files attached to a Kanboard task.")]
    pub async fn list_attachments(&self, Parameters(req): Parameters<ListAttachments>) -> String {
        tool_json(list_attachments_impl(&client(), req.task_id).await)
    }

    /// Download an attachment into the agent working directory.
    #[tool(description = "Download a Kanboard task attachment to a local file path.")]
    pub async fn get_attachment(&self, Parameters(req): Parameters<GetAttachment>) -> String {
        tool_json(get_attachment_impl(&client(), req.file_id, &req.output_path).await)
    }

    /// Delete an attachment from Kanboard.
    #[tool(description = "Delete a Kanboard task attachment.")]
    pub async fn delete_attachment(&self, Parameters(req): Parameters<DeleteAttachment>) -> String {
        tool_json(delete_attachment_impl(&client(), req.file_id).await)
    }

    /// Upload an agent-local file to a Kanboard task.
    #[tool(description = "Upload a local file as a Kanboard task attachment.")]
    pub async fn upload_attachment(&self, Parameters(req): Parameters<UploadAttachment>) -> String {
        tool_json(
            upload_attachment_impl(
                &client(),
                req.project_id,
                req.task_id,
                &req.path,
                req.filename.as_deref(),
            )
            .await,
        )
    }

    /// Add a comment as the authenticated Kanboard user.
    #[tool(description = "Add a comment to a Kanboard task as the authenticated worker user.")]
    pub async fn add_comment(&self, Parameters(req): Parameters<AddComment>) -> String {
        tool_json(add_comment_impl(&client(), req.task_id, &req.comment).await)
    }

    /// Create a subtask and optionally assign it to a roster user.
    #[tool(description = "Add a subtask to a Kanboard task and optionally assign it to a user.")]
    pub async fn add_subtask(&self, Parameters(req): Parameters<AddSubtask>) -> String {
        tool_json(
            add_subtask_impl(&client(), req.task_id, &req.title, req.assignee.as_deref()).await,
        )
    }

    /// Move a task to one of the configured board columns.
    #[tool(
        description = "Move a task to one of the configured board columns: todo, working, blocked, or done."
    )]
    pub async fn move_column(&self, Parameters(req): Parameters<MoveColumn>) -> String {
        tool_json(
            move_column_impl(
                &client(),
                req.project_id,
                req.task_id,
                &req.column,
                req.swimlane_id.unwrap_or(0),
            )
            .await,
        )
    }
}

#[tool_handler]
impl ServerHandler for KanboardMcpServer {
    /// Return server capabilities and agent-facing instructions.
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_instructions(TOOL_INSTRUCTIONS)
    }
}

/// List all files attached to a Kanboard task.
pub async fn list_attachments_impl<C: KanboardApi>(client: &C, task_id: i64) -> AppResult<Value> {
    Ok(Value::Array(
        client.get_all_task_files(&json!(task_id)).await?,
    ))
}

/// Download a Kanboard attachment to a confined local path.
pub async fn get_attachment_impl<C: KanboardApi>(
    client: &C,
    file_id: i64,
    output_path: &str,
) -> AppResult<Value> {
    let content = client.download_task_file(&json!(file_id)).await?;
    let path = confined_path(output_path)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).await?;
    }
    fs::write(&path, &content).await?;
    Ok(json!({"file_id": file_id, "path": path, "bytes": content.len()}))
}

/// Delete a Kanboard task attachment by file id.
pub async fn delete_attachment_impl<C: KanboardApi>(client: &C, file_id: i64) -> AppResult<Value> {
    client.remove_task_file(&json!(file_id)).await?;
    Ok(json!({"file_id": file_id, "deleted": true}))
}

/// Upload a confined local file to a Kanboard task.
pub async fn upload_attachment_impl<C: KanboardApi>(
    client: &C,
    project_id: i64,
    task_id: i64,
    path: &str,
    filename: Option<&str>,
) -> AppResult<Value> {
    let source = confined_path(path)?;
    let content = fs::read(&source).await?;
    let filename = filename
        .map(str::to_string)
        .or_else(|| {
            source
                .file_name()
                .map(|name| name.to_string_lossy().to_string())
        })
        .unwrap_or_else(|| "attachment".to_string());
    let file_id = client
        .create_task_file(&json!(project_id), &json!(task_id), &filename, &content)
        .await?;
    Ok(json!({"file_id": file_id, "task_id": task_id, "filename": filename}))
}

/// Add a comment to a Kanboard task as the authenticated user.
pub async fn add_comment_impl<C: KanboardApi>(
    client: &C,
    task_id: i64,
    comment: &str,
) -> AppResult<Value> {
    let user = client.get_me().await?;
    let comment_id = client
        .create_comment(&json!(task_id), &value_id(&user), comment)
        .await?;
    Ok(json!({"comment_id": comment_id, "task_id": task_id}))
}

/// Create a Kanboard subtask with an optional assignee username.
pub async fn add_subtask_impl<C: KanboardApi>(
    client: &C,
    task_id: i64,
    title: &str,
    assignee: Option<&str>,
) -> AppResult<Value> {
    let user_id = match assignee {
        Some(username) if !username.is_empty() => {
            value_id(&client.get_user_by_name(username).await?)
        }
        _ => json!(0),
    };
    let subtask_id = client
        .create_subtask(&json!(task_id), title, &user_id, 0)
        .await?;
    Ok(json!({"subtask_id": subtask_id, "task_id": task_id, "title": title, "assignee": assignee}))
}

/// Move a task to a configured logical column.
pub async fn move_column_impl<C: KanboardApi>(
    client: &C,
    project_id: i64,
    task_id: i64,
    column: &str,
    swimlane_id: i64,
) -> AppResult<Value> {
    if !["todo", "working", "blocked", "done"].contains(&column) {
        return Err(AppError::Kanboard(
            "column must be one of: todo, working, blocked, done".to_string(),
        ));
    }
    let board = configured_board(project_id)?;
    let lookup = column_lookup(
        &client.get_columns(&json!(project_id)).await?,
        &[
            ("todo", &board.todo),
            ("working", &board.working),
            ("blocked", &board.blocked),
            ("done", &board.done),
        ],
    )?;
    let target = match column {
        "todo" => lookup.todo,
        "working" => lookup.working,
        "blocked" => lookup.blocked,
        "done" => lookup.done,
        _ => unreachable!(),
    };
    let task = client.get_task(&json!(task_id)).await?;
    let target_swimlane = task
        .get("swimlane_id")
        .cloned()
        .unwrap_or_else(|| json!(swimlane_id));
    client
        .move_task_to_column(
            &json!(project_id),
            &json!(task_id),
            &value_id(&target),
            &target_swimlane,
            1,
        )
        .await?;
    Ok(json!({
        "task_id": task_id,
        "column": column,
        "column_title": target.get("title").and_then(Value::as_str).unwrap_or(""),
        "column_id": value_id(&target),
    }))
}

/// Build a Kanboard client from MCP environment variables.
fn client() -> KanboardClient {
    KanboardClient::new(
        env::var("KANBOARD_URL").unwrap_or_default(),
        env::var("KANBOARD_USER").unwrap_or_default(),
        env::var("KANBOARD_TOKEN").unwrap_or_default(),
    )
}

/// Find the configured board mapping for a Kanboard project id.
fn configured_board(project_id: i64) -> AppResult<BoardConfig> {
    let boards: Vec<BoardConfig> =
        serde_json::from_str(&env::var("KANBOARD_WORKER_BOARDS").unwrap_or_else(|_| "[]".into()))?;
    boards
        .into_iter()
        .find(|board| board.id.to_string().trim_matches('"') == project_id.to_string())
        .ok_or_else(|| {
            AppError::Kanboard(format!(
                "Project {project_id} is not configured for this worker"
            ))
        })
}

/// Return the configured agent root for file tools.
pub fn agent_root() -> PathBuf {
    env::var("KANBOARD_AGENT_PWD")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("."))
        .canonicalize()
        .unwrap_or_else(|_| PathBuf::from("."))
}

/// Resolve a local path and reject paths outside the agent root.
pub fn confined_path(path: &str) -> AppResult<PathBuf> {
    let root = agent_root();
    let target = PathBuf::from(path);
    let target = if target.is_absolute() {
        target
    } else {
        root.join(target)
    };
    let parent = target.parent().unwrap_or(&root);
    let canonical_parent = parent
        .canonicalize()
        .unwrap_or_else(|_| parent.to_path_buf());
    if !canonical_parent.starts_with(&root) {
        return Err(AppError::Kanboard(format!(
            "Path outside configured agent.pwd: {path}"
        )));
    }
    Ok(target)
}

/// Encode tool results as JSON strings expected by RMCP tool responses.
fn tool_json(result: AppResult<Value>) -> String {
    match result {
        Ok(value) => serde_json::to_string(&value).unwrap_or_else(|_| "{}".to_string()),
        Err(error) => serde_json::to_string(&json!({"error": error.to_string()})).unwrap(),
    }
}
